use crate::models::StateMachine;
use super::CodeGenerator;
use anyhow::Result;
use crate::models::Language;

pub struct GoGenerator;

impl CodeGenerator for GoGenerator {
    fn language(&self) -> Language { Language::Go }
    fn file_extension(&self) -> &str { "go" }

    fn generate(&self, sm: &StateMachine) -> Result<String> {
        let name = pascal(&sm.name);
        let pkg = name.to_lowercase();

        let mut out = format!("// Generated by StateForge\npackage {}\n\n", pkg);

        // State type + iota
        out.push_str(&format!("type {}State int\n\n", name));
        out.push_str("const (\n");
        for (i, state) in sm.states.iter().enumerate() {
            let suffix = if i == 0 { " = iota" } else { "" };
            out.push_str(&format!("    {}State{}{}\n", name, pascal(&state.name), suffix));
        }
        out.push_str(")\n\n");

        // String method
        out.push_str(&format!("func (s {}State) String() string {{\n    switch s {{\n", name));
        for state in &sm.states {
            out.push_str(&format!("    case {}State{}:\n        return \"{}\"\n",
                name, pascal(&state.name), state.name));
        }
        out.push_str("    default:\n        return \"unknown\"\n    }\n}\n\n");

        // Event type + iota
        let events: Vec<_> = sm.transitions.iter()
            .filter_map(|t| t.event.clone())
            .collect::<std::collections::HashSet<_>>()
            .into_iter()
            .collect();

        if !events.is_empty() {
            out.push_str(&format!("type {}Event int\n\nconst (\n", name));
            for (i, event) in events.iter().enumerate() {
                let suffix = if i == 0 { " = iota" } else { "" };
                out.push_str(&format!("    {}Event{}{}\n", name, pascal(event), suffix));
            }
            out.push_str(")\n\n");
        }

        // FSM struct
        out.push_str(&format!(
            "type {}Machine struct {{\n    State {}State\n}}\n\n",
            name, name
        ));

        // Transition function
        out.push_str(&format!(
            "func (m *{}Machine) Transition(event {}Event) bool {{\n    switch m.State {{\n",
            name, name
        ));

        for state in &sm.states {
            let outgoing = sm.outgoing(&state.id);
            if outgoing.is_empty() { continue; }

            out.push_str(&format!("    case {}State{}:\n        switch event {{\n", name, pascal(&state.name)));
            for t in outgoing {
                let event = t.event.as_deref().unwrap_or("Any");
                let to_state = sm.state_by_id(&t.to_state).map(|s| s.name.as_str()).unwrap_or("Unknown");
                out.push_str(&format!("        case {}Event{}:\n            m.State = {}State{}\n            return true\n",
                    name, pascal(event), name, pascal(to_state)));
            }
            out.push_str("        }\n");
        }

        out.push_str("    }\n    return false\n}\n\n");

        // Constructor
        let initial = sm.initial_state.as_ref()
            .and_then(|id| sm.state_by_id(id))
            .map(|s| s.name.as_str())
            .unwrap_or("Idle");

        out.push_str(&format!(
            "func New{}Machine() *{}Machine {{\n    return &{}Machine{{State: {}State{}}}\n}}\n",
            name, name, name, name, pascal(initial)
        ));

        Ok(out)
    }
}

fn pascal(s: &str) -> String {
    s.split(|c: char| !c.is_alphanumeric())
        .filter(|p| !p.is_empty())
        .map(|p| {
            let mut c = p.chars();
            match c.next() {
                None => String::new(),
                Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
            }
        })
        .collect()
}
