#![allow(unused_imports)]
use crate::models::{StateMachine, StateKind};
use super::CodeGenerator;
use anyhow::Result;
use crate::models::Language;

pub struct KotlinGenerator;

impl CodeGenerator for KotlinGenerator {
    fn language(&self) -> Language { Language::Kotlin }
    fn file_extension(&self) -> &str { "kt" }

    fn generate(&self, sm: &StateMachine) -> Result<String> {
        let name = pascal(&sm.name);
        let mut out = String::from("// Generated by StateForge\n\nimport androidx.lifecycle.ViewModel\nimport kotlinx.coroutines.flow.MutableStateFlow\nimport kotlinx.coroutines.flow.StateFlow\n\n");

        // Sealed class state
        out.push_str(&format!("sealed class {}UiState {{\n", name));
        for state in &sm.states {
            let sname = pascal(&state.name);
            let transitions_out = sm.outgoing(&state.id);
            if transitions_out.iter().any(|t| sm.state_by_id(&t.to_state)
                .map(|s| s.metadata.contains_key("payload")).unwrap_or(false))
            {
                out.push_str(&format!("    data class {}(val data: Any? = null) : {}UiState()\n", sname, name));
            } else {
                out.push_str(&format!("    object {} : {}UiState()\n", sname, name));
            }
        }
        out.push_str("}\n\n");

        // Sealed intent
        let events: Vec<_> = sm.transitions.iter()
            .filter_map(|t| t.event.as_ref())
            .collect::<std::collections::BTreeSet<_>>()
            .into_iter()
            .collect();

        if !events.is_empty() {
            out.push_str(&format!("sealed class {}Intent {{\n", name));
            for event in &events {
                out.push_str(&format!("    object {} : {}Intent()\n", pascal(event), name));
            }
            out.push_str("}\n\n");
        }

        // ViewModel
        out.push_str(&format!(
            "class {}ViewModel : ViewModel() {{\n    private val _state = MutableStateFlow<{}UiState>({}UiState.{})\n    val state: StateFlow<{}UiState> = _state\n\n",
            name, name, name,
            pascal(sm.initial_state.as_deref().and_then(|id| sm.state_by_id(id))
                .or(sm.states.first()).map(|s| s.name.as_str()).unwrap_or("Idle")),
            name
        ));
        out.push_str(&format!("    fun handleIntent(intent: {}Intent) {{\n        when (intent) {{\n", name));
        // The next state depends on the current one; setting every target of an
        // event in a row left the machine in whichever came last.
        for event in &events {
            out.push_str(&format!("            is {}Intent.{} -> _state.value = when (_state.value) {{\n", name, pascal(event)));
            let mut seen = std::collections::BTreeSet::new();
            for t in sm.transitions.iter().filter(|t| t.event.as_deref() == Some(event)) {
                let from = sm.state_by_id(&t.from_state).map(|s| pascal(&s.name)).unwrap_or_default();
                let to = sm.state_by_id(&t.to_state).map(|s| pascal(&s.name)).unwrap_or_default();
                if seen.insert(from.clone()) {
                    out.push_str(&format!("                is {name}UiState.{from} -> {name}UiState.{to}\n"));
                }
            }
            out.push_str("                else -> _state.value\n            }\n");
        }
        out.push_str("        }\n    }\n}\n");

        Ok(out)
    }
}

fn pascal(s: &str) -> String {
    s.split(|c: char| !c.is_alphanumeric())
        .filter(|p| !p.is_empty())
        .map(|p| {
            let mut c = p.chars();
            match c.next() {
                None => String::new(),
                Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
            }
        })
        .collect()
}
