use crate::models::{StateMachine, StateKind};
use super::CodeGenerator;
use anyhow::Result;
use crate::models::Language;

pub struct KotlinGenerator;

impl CodeGenerator for KotlinGenerator {
    fn language(&self) -> Language { Language::Kotlin }
    fn file_extension(&self) -> &str { "kt" }

    fn generate(&self, sm: &StateMachine) -> Result<String> {
        let name = pascal(&sm.name);
        let mut out = String::from("// Generated by StateForge\n\n");

        // Sealed class state
        out.push_str(&format!("sealed class {}UiState {{\n", name));
        for state in &sm.states {
            let sname = pascal(&state.name);
            let transitions_out = sm.outgoing(&state.id);
            if transitions_out.iter().any(|t| sm.state_by_id(&t.to_state)
                .map(|s| s.metadata.contains_key("payload")).unwrap_or(false))
            {
                out.push_str(&format!("    data class {}(val data: Any? = null) : {}UiState()\n", sname, name));
            } else {
                out.push_str(&format!("    object {} : {}UiState()\n", sname, name));
            }
        }
        out.push_str("}\n\n");

        // Sealed intent
        let events: Vec<_> = sm.transitions.iter()
            .filter_map(|t| t.event.as_ref())
            .collect::<std::collections::HashSet<_>>()
            .into_iter()
            .collect();

        if !events.is_empty() {
            out.push_str(&format!("sealed class {}Intent {{\n", name));
            for event in &events {
                out.push_str(&format!("    object {} : {}Intent()\n", pascal(event), name));
            }
            out.push_str("}\n\n");
        }

        // ViewModel
        out.push_str(&format!(
            "class {}ViewModel : ViewModel() {{\n    private val _state = MutableStateFlow<{}UiState>({}UiState.{})\n    val state: StateFlow<{}UiState> = _state\n\n",
            name, name, name,
            pascal(&sm.states.first().map(|s| s.name.as_str()).unwrap_or("Idle")),
            name
        ));
        out.push_str(&format!("    fun handleIntent(intent: {}Intent) {{\n        when (intent) {{\n", name));
        for event in &events {
            out.push_str(&format!("            is {}Intent.{} -> {{\n", name, pascal(event)));
            let transitions: Vec<_> = sm.transitions.iter()
                .filter(|t| t.event.as_deref() == Some(event))
                .collect();
            for t in transitions {
                let to_state = sm.state_by_id(&t.to_state).map(|s| pascal(&s.name)).unwrap_or_default();
                out.push_str(&format!("                _state.value = {}UiState.{}\n", name, to_state));
            }
            out.push_str("            }\n");
        }
        out.push_str("        }\n    }\n}\n");

        Ok(out)
    }
}

fn pascal(s: &str) -> String {
    s.split(|c: char| !c.is_alphanumeric())
        .filter(|p| !p.is_empty())
        .map(|p| {
            let mut c = p.chars();
            match c.next() {
                None => String::new(),
                Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
            }
        })
        .collect()
}
