use std::collections::BTreeSet;

use anyhow::Result;

use super::CodeGenerator;
use crate::models::{Language, StateMachine};

pub struct RustGenerator;

/// `not Ok` → `NotOk`, `order_paid` → `OrderPaid`, `CANCEL` → `Cancel`, `2fa` → `_2fa`
fn ident(raw: &str) -> String {
    let mut out = String::new();
    for part in raw.split(|c: char| !c.is_alphanumeric()).filter(|p| !p.is_empty()) {
        // All caps is a shouted word, not an acronym inside CamelCase; Rust warns on it.
        let part = if part.len() > 1 && part.chars().all(|c| !c.is_lowercase()) { part.to_lowercase() } else { part.to_string() };
        let mut chars = part.chars();
        if let Some(first) = chars.next() {
            out.extend(first.to_uppercase());
            out.push_str(chars.as_str());
        }
    }
    if out.is_empty() {
        out.push_str("Unnamed");
    }
    if out.starts_with(|c: char| c.is_ascii_digit()) {
        out.insert(0, '_');
    }
    out
}

impl CodeGenerator for RustGenerator {
    fn language(&self) -> Language { Language::Rust }
    fn file_extension(&self) -> &str { "rs" }

    fn generate(&self, sm: &StateMachine) -> Result<String> {
        let base = ident(sm.name.trim_end_matches("Machine"));
        let state_ty = if base.ends_with("State") { base.clone() } else { format!("{base}State") };
        let event_ty = format!("{}Event", base.trim_end_matches("State"));
        let name_of = |id: &str| sm.state_by_id(id).map(|s| ident(&s.name)).unwrap_or_default();
        let events: BTreeSet<String> = sm.transitions.iter()
            .map(|t| ident(t.event.as_deref().unwrap_or("Auto")))
            .collect();

        let mut out = String::from("// Generated by StateForge\n\n");
        out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]\n");
        out.push_str(&format!("pub enum {state_ty} {{\n"));
        for s in &sm.states {
            out.push_str(&format!("    {},\n", ident(&s.name)));
        }
        out.push_str("}\n\n");

        if !events.is_empty() {
            out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]\n");
            out.push_str(&format!("pub enum {event_ty} {{\n"));
            for e in &events {
                out.push_str(&format!("    {e},\n"));
            }
            out.push_str("}\n\n");
        }

        out.push_str(&format!("impl {state_ty} {{\n"));
        if let Some(initial) = sm.initial_state.as_deref() {
            out.push_str(&format!("    pub const INITIAL: Self = Self::{};\n\n", name_of(initial)));
        }
        if !events.is_empty() {
            out.push_str("    /// The next state, or `None` when the event is not allowed in this state.\n");
            out.push_str(&format!("    pub fn next(self, event: {event_ty}) -> Option<Self> {{\n"));
            out.push_str("        match (self, event) {\n");
            let mut seen = BTreeSet::new();
            for t in &sm.transitions {
                let (from, to) = (name_of(&t.from_state), name_of(&t.to_state));
                let ev = ident(t.event.as_deref().unwrap_or("Auto"));
                // A second target for the same state and event would be an
                // unreachable arm; the extraction found both, so keep it visible.
                if seen.insert((from.clone(), ev.clone())) {
                    out.push_str(&format!("            (Self::{from}, {event_ty}::{ev}) => Some(Self::{to}),\n"));
                } else {
                    out.push_str(&format!("            // also found: (Self::{from}, {event_ty}::{ev}) => Self::{to}\n"));
                }
            }
            out.push_str("            _ => None,\n        }\n    }\n\n");
        }
        let finals: Vec<String> = sm.states.iter().filter(|s| s.is_terminal()).map(|s| format!("Self::{}", ident(&s.name))).collect();
        out.push_str("    pub fn is_final(self) -> bool {\n");
        if finals.is_empty() {
            out.push_str("        false\n");
        } else {
            out.push_str(&format!("        matches!(self, {})\n", finals.join(" | ")));
        }
        out.push_str("    }\n}\n");
        Ok(out)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn identifiers_are_valid_rust() {
        assert_eq!(ident("not Ok"), "NotOk");
        assert_eq!(ident("order_paid"), "OrderPaid");
        assert_eq!(ident("2fa"), "_2fa");
        assert_eq!(ident("CANCEL"), "Cancel");
        assert_eq!(ident("ORDER_PAID"), "OrderPaid");
    }
}
