use crate::models::{StateMachine, StateKind};
use super::CodeGenerator;
use anyhow::Result;
use crate::models::Language;

pub struct SwiftGenerator;

impl CodeGenerator for SwiftGenerator {
    fn language(&self) -> Language { Language::Swift }
    fn file_extension(&self) -> &str { "swift" }

    fn generate(&self, sm: &StateMachine) -> Result<String> {
        let name = pascal(&sm.name);
        let mut out = format!("// Generated by StateForge\nimport Foundation\n\n");

        // State enum
        out.push_str(&format!("enum {}State: Equatable {{\n", name));
        for state in &sm.states {
            out.push_str(&format!("    case {}\n", camel(&state.name)));
        }
        out.push_str("}\n\n");

        // Event enum
        let events: Vec<_> = sm.transitions.iter()
            .filter_map(|t| t.event.as_ref())
            .collect::<std::collections::HashSet<_>>()
            .into_iter()
            .collect();

        if !events.is_empty() {
            out.push_str(&format!("enum {}Action {{\n", name));
            for event in &events {
                out.push_str(&format!("    case {}\n", camel(event)));
            }
            out.push_str("}\n\n");
        }

        // Context (if any)
        if let Some(ref ctx) = sm.context_type {
            out.push_str(&format!("struct {}Context {{\n    // {}\n}}\n\n", name, ctx));
        }

        // Reducer function
        out.push_str(&format!(
            "@discardableResult\nfunc {}Reducer(\n    state: inout {}State,\n    action: {}Action\n) -> {}State {{\n",
            camel(&name), name, name, name
        ));
        out.push_str("    switch state {\n");

        for state in &sm.states {
            let outgoing = sm.outgoing(&state.id);
            out.push_str(&format!("    case .{}:\n", camel(&state.name)));
            if outgoing.is_empty() {
                out.push_str("        break\n");
            } else {
                out.push_str("        switch action {\n");
                for t in outgoing {
                    let event = t.event.as_deref().unwrap_or("any");
                    let to_state = sm.state_by_id(&t.to_state).map(|s| s.name.as_str()).unwrap_or("unknown");
                    out.push_str(&format!("        case .{}:\n", camel(event)));
                    if !t.actions.is_empty() {
                        for act in &t.actions {
                            out.push_str(&format!("            // {}\n", act));
                        }
                    }
                    out.push_str(&format!("            state = .{}\n", camel(to_state)));
                    if let Some(ref guard) = t.guard {
                        out.push_str(&format!("            // guard: {}\n", guard));
                    }
                }
                out.push_str("        }\n");
            }
        }

        out.push_str("    }\n    return state\n}\n");
        Ok(out)
    }
}

fn pascal(s: &str) -> String {
    s.split(|c: char| !c.is_alphanumeric())
        .filter(|p| !p.is_empty())
        .map(|p| {
            let mut c = p.chars();
            match c.next() {
                None => String::new(),
                Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
            }
        })
        .collect()
}

fn camel(s: &str) -> String {
    let p = pascal(s);
    let mut c = p.chars();
    match c.next() {
        None => String::new(),
        Some(f) => f.to_lowercase().collect::<String>() + c.as_str(),
    }
}
