use crate::models::StateMachine;
use super::CodeGenerator;
use anyhow::Result;
use crate::models::Language;

pub struct TypeScriptGenerator;

impl CodeGenerator for TypeScriptGenerator {
    fn language(&self) -> Language { Language::TypeScript }
    fn file_extension(&self) -> &str { "ts" }

    fn generate(&self, sm: &StateMachine) -> Result<String> {
        let name = pascal(&sm.name);
        let mut out = String::from("// Generated by StateForge\n\n");

        // State union type
        let state_names: Vec<_> = sm.states.iter().map(|s| format!("'{}'", s.name)).collect();
        out.push_str(&format!("export type {}State = {};\n\n", name, state_names.join(" | ")));

        // Event union type
        let events: Vec<_> = sm.transitions.iter()
            .filter_map(|t| t.event.clone())
            .collect::<std::collections::HashSet<_>>()
            .into_iter()
            .collect();

        if !events.is_empty() {
            let event_types: Vec<_> = events.iter().map(|e| format!("{{ type: '{}' }}", e)).collect();
            out.push_str(&format!("export type {}Event = {};\n\n", name, event_types.join("\n  | ")));
        }

        // Context interface
        out.push_str(&format!("export interface {}Context {{\n  state: {}State;\n", name, name));
        if let Some(ref ctx) = sm.context_type {
            out.push_str(&format!("  // {}\n", ctx));
        }
        out.push_str("}\n\n");

        // Transition map
        out.push_str(&format!("export const {}Transitions: Record<{}State, Partial<Record<string, {}State>>> = {{\n", name, name, name));
        for state in &sm.states {
            let outgoing = sm.outgoing(&state.id);
            out.push_str(&format!("  '{}': {{\n", state.name));
            for t in &outgoing {
                let to = sm.state_by_id(&t.to_state).map(|s| s.name.as_str()).unwrap_or("unknown");
                let event = t.event.as_deref().unwrap_or("*");
                out.push_str(&format!("    '{}': '{}',\n", event, to));
            }
            out.push_str("  },\n");
        }
        out.push_str("};\n\n");

        // Reducer function
        out.push_str(&format!(
            "export function {}Reducer(\n  state: {}State,\n  event: {}Event\n): {}State {{\n",
            camel(&name), name, name, name
        ));
        out.push_str(&format!("  const transitions = {}Transitions[state];\n", name));
        out.push_str("  const next = transitions[event.type] ?? transitions['*'];\n");
        out.push_str("  return next ?? state;\n}\n\n");

        // XState-compatible machine config
        out.push_str(&format!("// XState-compatible machine configuration\nexport const {}Machine = {{\n  id: '{}',\n  initial: '{}' as const,\n  states: {{\n",
            camel(&name), camel(&sm.name),
            sm.initial_state.as_ref()
                .and_then(|id| sm.state_by_id(id))
                .map(|s| s.name.as_str())
                .unwrap_or("idle")
        ));

        for state in &sm.states {
            let outgoing = sm.outgoing(&state.id);
            out.push_str(&format!("    '{}': {{\n", state.name));
            if !outgoing.is_empty() {
                out.push_str("      on: {\n");
                for t in &outgoing {
                    let to = sm.state_by_id(&t.to_state).map(|s| s.name.as_str()).unwrap_or("unknown");
                    let event = t.event.as_deref().unwrap_or("NEXT");
                    out.push_str(&format!("        {}: {{ target: '{}' }},\n", event, to));
                }
                out.push_str("      },\n");
            }
            out.push_str("    },\n");
        }
        out.push_str("  },\n};\n");

        Ok(out)
    }
}

fn pascal(s: &str) -> String {
    s.split(|c: char| !c.is_alphanumeric())
        .filter(|p| !p.is_empty())
        .map(|p| {
            let mut c = p.chars();
            match c.next() {
                None => String::new(),
                Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
            }
        })
        .collect()
}

fn camel(s: &str) -> String {
    let p = pascal(s);
    let mut c = p.chars();
    match c.next() {
        None => String::new(),
        Some(f) => f.to_lowercase().collect::<String>() + c.as_str(),
    }
}
